/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobilex_lookit_LookActivity */

#ifndef _Included_com_mobilex_lookit_LookActivity
#define _Included_com_mobilex_lookit_LookActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mobilex_lookit_LookActivity
 * Method:    initCV
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mobilex_lookit_LookActivity_initCV
  (JNIEnv *, jobject);

/*
 * Class:     com_mobilex_lookit_LookActivity
 * Method:    addMemo
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_mobilex_lookit_LookActivity_addMemo
  (JNIEnv *, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
