/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobilex_lookit_utils_Matcher */

#ifndef _Included_com_mobilex_lookit_utils_Matcher
#define _Included_com_mobilex_lookit_utils_Matcher
#ifdef __cplusplus
extern "C" {
#endif
#undef com_mobilex_lookit_utils_Matcher_MIN_PRIORITY
#define com_mobilex_lookit_utils_Matcher_MIN_PRIORITY 1L
#undef com_mobilex_lookit_utils_Matcher_NORM_PRIORITY
#define com_mobilex_lookit_utils_Matcher_NORM_PRIORITY 5L
#undef com_mobilex_lookit_utils_Matcher_MAX_PRIORITY
#define com_mobilex_lookit_utils_Matcher_MAX_PRIORITY 10L
/*
 * Class:     com_mobilex_lookit_utils_Matcher
 * Method:    getResult
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mobilex_lookit_utils_Matcher_getResult
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_mobilex_lookit_utils_Matcher
 * Method:    matchQuery
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_mobilex_lookit_utils_Matcher_matchQuery
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
