/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobilex_lookit_CaptureActivity */

#ifndef _Included_com_mobilex_lookit_CaptureActivity
#define _Included_com_mobilex_lookit_CaptureActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mobilex_lookit_CaptureActivity
 * Method:    drawAndGetInterest
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_mobilex_lookit_CaptureActivity_drawAndGetInterest
  (JNIEnv *, jobject, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
